const COGNITIVE_WEIGHT_DEFAULT = 2;
const NUM_DIMENSIONS_DEFAULT = 2;
const NUM_PARTICLES_DEFAULT = 20;
const SOCIAL_WEIGHT_DEFAULT = 2;
const SQUARED_POWER = 2;

module.exports = {
  COGNITIVE_WEIGHT_DEFAULT: COGNITIVE_WEIGHT_DEFAULT,
  NUM_DIMENSIONS_DEFAULT: NUM_DIMENSIONS_DEFAULT,
  NUM_PARTICLES_DEFAULT: NUM_PARTICLES_DEFAULT,
  SOCIAL_WEIGHT_DEFAULT: SOCIAL_WEIGHT_DEFAULT,
  SQUARED_POWER: SQUARED_POWER,
};
